version: "2"
services: 
  tattva:
    build: .
    image: tattva
    ports:
      - 8081:8081
    expose:
      - 8081
    depends_on:
      - mongo
    links:
      - mongo
    environment:
       MONGO_URL: 'mongodb://mongo/TattvaDB'
  mongo:
    image: mongo
    ports:
      - 27017:27017          